# Generated by Django 3.1.5 on 2021-07-18 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=50, verbose_name='Участок')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('service_type', models.CharField(choices=[('electricity', 'Электричество'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Счетчик',
                'verbose_name_plural': 'Счетчики',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('electricity_1', 'Электричество (тариф 1)'), ('electricity_2', 'Электричество (тариф 2)'), ('electricity_3', 'Электричество (тариф 3)'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Услуга')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Окончание действия')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'unique_together': {('service', 'start_date')},
            },
        ),
        migrations.CreateModel(
            name='CounterHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('electricity_1', 'Электричество (тариф 1)'), ('electricity_2', 'Электричество (тариф 2)'), ('electricity_3', 'Электричество (тариф 3)'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Услуга')),
                ('date', models.DateField(verbose_name='Дата')),
                ('value', models.IntegerField(verbose_name='Показание')),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.counter', verbose_name='Счетчик')),
            ],
            options={
                'verbose_name': 'Показание',
                'verbose_name_plural': 'Показания',
            },
        ),
    ]
