# Generated by Django 3.1.5 on 2021-07-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20210718_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='service_type',
            field=models.CharField(choices=[('electricity_1_tariff', 'Электричество однотарифный'), ('electricity_2_tariff', 'Электричество двухтарифный'), ('electricity_3_tariff', 'Электричество трехтарифный'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='counterhistory',
            name='service',
            field=models.CharField(choices=[('electricity_1_1', 'Электричество однотарифный тариф'), ('electricity_2_1', 'Электричество двухтарифный тариф 1'), ('electricity_2_2', 'Электричество двухтарифный тариф 2'), ('electricity_3_1', 'Электричество трехтарифный тариф 1'), ('electricity_3_2', 'Электричество трехтарифный тариф 2'), ('electricity_3_3', 'Электричество трехтарифный тариф 3'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='service',
            field=models.CharField(choices=[('electricity_1_1', 'Электричество однотарифный тариф'), ('electricity_2_1', 'Электричество двухтарифный тариф 1'), ('electricity_2_2', 'Электричество двухтарифный тариф 2'), ('electricity_3_1', 'Электричество трехтарифный тариф 1'), ('electricity_3_2', 'Электричество трехтарифный тариф 2'), ('electricity_3_3', 'Электричество трехтарифный тариф 3'), ('water', 'Вода питьевая')], max_length=50, verbose_name='Услуга'),
        ),
    ]
