version: '2.1'

services:
  app:
    volumes:
      - ./:/app
      - ./media_storage:/mnt/media
    command: "python ./manage.py runserver 0.0.0.0:8000"
    ports:
      - "8888:8000"

  nginx:
    volumes:
      - ./media_storage:/mnt/media
