# Generated by Django 3.1.5 on 2021-01-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('short_text', models.TextField(verbose_name='Короткое описание')),
                ('long_text', models.TextField(verbose_name='Полный текст')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
