# Generated by Django 3.1.5 on 2021-01-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Описание')),
                ('stroi_staff_only', models.BooleanField(verbose_name='Показывать только членам СНТ')),
                ('slug', models.SlugField(verbose_name='URL slug')),
            ],
            options={
                'verbose_name': 'Раздел сайта',
                'verbose_name_plural': 'Разделы сайта',
            },
        ),
        migrations.CreateModel(
            name='NewsEntryBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_short_text', models.TextField(verbose_name='Короткое описание')),
                ('news_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_binds', to='news.newsentry', verbose_name='Новость')),
                ('site_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_binds', to='news.sitesection', verbose_name='Раздел сайта')),
            ],
        ),
    ]
