# Generated by Django 3.1.5 on 2021-01-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsentrybind_sitesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesection',
            name='title',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Описание'),
        ),
    ]
