# Generated by Django 3.1.5 on 2021-01-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210131_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='site_entries',
            field=models.ManyToManyField(related_name='news', through='news.NewsEntryBind', to='news.SiteSection', verbose_name='Разделы сайта'),
        ),
        migrations.AlterField(
            model_name='newsentrybind',
            name='custom_short_text',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
