# Generated by Django 3.1.5 on 2021-01-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210131_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsentry',
            old_name='site_entries',
            new_name='site_sections',
        ),
        migrations.AddField(
            model_name='newsentrybind',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='newsentrybind',
            name='custom_short_text',
            field=models.TextField(blank=True, null=True, verbose_name='Алтернативное описание (не обязательно)'),
        ),
    ]
