# Generated by Django 3.1.5 on 2021-01-31 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210131_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsentrybind',
            options={'verbose_name': 'Привязка к разделу', 'verbose_name_plural': 'Привязки к разделам'},
        ),
        migrations.AddField(
            model_name='sitesection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.sitesection', verbose_name='Родителький раздел'),
        ),
    ]
