# Generated by Django 3.1.5 on 2021-01-31 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210131_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsentry',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
    ]
