# Generated by Django 3.1.5 on 2021-02-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_mediafile_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(unique=True, upload_to='', verbose_name='Файл'),
        ),
    ]
