# Generated by Django 3.1.5 on 2021-02-04 13:51

from django.db import migrations, models
import django.utils.timezone
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210204_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(unique=True, upload_to=news.models.get_upload_prefix, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='newsentry',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
