# Generated by Django 3.1.5 on 2021-02-04 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210204_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата загрузки'),
        ),
    ]
