# Generated by Django 3.1.5 on 2021-02-04 14:15

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210204_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='members_only',
            field=models.BooleanField(default=False, verbose_name='Показывать только членам СНТ'),
        ),
        migrations.AddField(
            model_name='newsentry',
            name='not_members_placeholder',
            field=models.TextField(blank=True, null=True, verbose_name='Текст не для членов СНТ'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(unique=True, upload_to=news.models.get_upload_prefix, verbose_name='Документ'),
        ),
    ]
