# Generated by Django 3.1.5 on 2021-02-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20210204_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesection',
            name='order',
            field=models.IntegerField(default=100, verbose_name='Очередность'),
        ),
    ]
