# Generated by Django 3.1.5 on 2022-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_sitesection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsentry',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Альтернативный порядок'),
        ),
    ]
