# Generated by Django 3.1.5 on 2022-02-19 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0016_sitesection_order'),
        ('social', '0004_voting_votingvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votingvariant',
            options={'ordering': ('order', 'published_at'), 'verbose_name': 'Вариант ответов', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterField(
            model_name='voting',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voting', to='news.newsentry', verbose_name='Документ'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата голосования')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Голосовавший')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.votingvariant', verbose_name='Ответ')),
            ],
        ),
    ]
