# Generated by Django 3.1.5 on 2022-02-20 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_sitesection_order'),
        ('social', '0005_auto_20220219_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания'),
        ),
        migrations.AddField(
            model_name='voting',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AddField(
            model_name='voting',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='social.votingvariant', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='voting',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votings', to='news.newsentry', verbose_name='Документ'),
        ),
        migrations.AlterIndexTogether(
            name='voting',
            index_together={('start_at', 'end_at')},
        ),
    ]
