# Generated by Django 3.1.5 on 2022-03-04 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20220220_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voting',
            options={'verbose_name': 'Опрос', 'verbose_name_plural': 'Опросы'},
        ),
        migrations.AlterField(
            model_name='votingvariant',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='social.voting', verbose_name='Опрос'),
        ),
    ]
