# Generated by Django 3.1.5 on 2022-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20220304_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
